CREATE TABLE OrderItems (
    orderItemID INT PRIMARY KEY,
    orderID INT,
    menuItemID INT,
    sugarLevel INT,
    iceLevel INT,
    milkType VARCHAR(50),
    boba INT,
    lycheeJelly INT,
    grassJelly INT,
    pudding INT,
    aloeVera INT,
    redBean INT,
    coffeeJelly INT,
    coconutJelly INT,
    chiaSeeds INT,
    taroBalls INT,
    mangoStars INT,
    rainbowJelly INT,
    crystalBoba INT,
    cheeseFoam INT,
    whippedCream INT,
    oreoCrumbs INT,
    caramelDrizzle INT,
    matchaFoam INT,
    strawberryPoppingBoba INT,
    mangoPoppingBoba INT,
    blueberryPoppingBoba INT,
    passionfruitPoppingBoba INT,
    chocolateChips INT,
    peanutCrumble INT,
    marshmallows INT,
    cinnamonDust INT,
    honey INT,
    mintLeaves INT,
    quantity INT NOT NULL,
    FOREIGN KEY (orderID) REFERENCES Orders(orderID),
    FOREIGN KEY (menuItemID) REFERENCES MenuItems(menuItemID)
);
